name: Kustomize Build Action

on:
  workflow_dispatch:

jobs:
  Kustomize-Build:
    runs-on: ubuntu-latest
    steps:

      # - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # - name: Version Information
      #   run: kubectl version --short

      - name: Check out repository code
        uses: actions/checkout@v2
      # - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "üñ•Ô∏è The workflow is now ready to build your code on the runner."

      - name: Run Kustomize build
        # id: kustomize-build
        uses: ./.github/actions/kustomize-build
        with:
          build-path: '.'
          output-file: 'kustomize.yaml'
          upload-artifact-name: 'kustomize'

      # - name: Build YAML
      #   run: kubectl kustomize > kustomize.yaml

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # - name: Upload Kustomize YAML
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: kustomize
      #     path: kustomize.yaml

      # - run: echo "üçè This job's status is ${{ job.status }}."
